### ISSUE TITLE
Bump version to 6.0.0

### ISSUE THREAD

**Issue by zacanger** [gxrsti/alert#10]
Hey, would you mind bumping the package version to v6, and optionally (ideally) unpublishing 5.1.5? That would reduce the potential for people to install the old version, unless they're jumping major versions without bothering to check, in which case, there's no help for them. `npm unpublish alert@5.1.5 && npm version major`.

**Comment by gxrsti** [comment]
Hey @zacanger, 
I could have thought of that...
unfortunately I cannot unpublish v5.1.5 anymore due to the unpublish policy (has dependents). I tried it as I thought it will be possible until 3 days after publishing but it isn't.

I would think that anyone updating dependencies is checking if everything still works after.

**Comment by zacanger** [comment]
Oh, right, npm makes that annoying if a package has dependents
> Anyway what I can offer is publishing a v5.1.6 with the old code and then bump to v6 for the new package.
That would be great, I'd really appreciate it. I have no idea what tech bootcamp or tutorial is still using this package after being deprecated for a year, but I'm hoping to avoid breaking them as much as possible. Chances are, if it's a bunch of students, they don't think to check what's in their package updates.

**Comment by gxrsti** [comment]
Will do this once I'm home!

**Comment by gxrsti** [comment]
Hey @zacanger, 
I couldn't make it yesterday but i just released v5.1.6 and the new v6.0.0 now. Thanks once again for your help!

**Comment by zacanger** [comment]
Thank you!
